name: Deploy Server

on:
  push:
    branches:
      - master
    paths:
      - "server/**"
      - ".github/workflows/server.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add server remote origin
        run: git remote add rustic-medico-api https://heroku:${{ secrets.HEROKU_API_TOKEN }}@git.heroku.com/${{ secrets.HEROKU_BACKEND_APP_NAME }}.git
      - name: Push server to remote origin
        run: git push rustic-medico-api `git subtree split --prefix server master`:refs/heads/master --force